### PR TITLE
fix: fix typo in modules

### PR DESCRIPTION
**Pull request by mehalter**
Sorry! Left a bad typo in my last PR! Just tested these changes fully and they are good to go! Sorry again 😢

### CODE REVIEW

**Comment by tobihans** [comment]
I just got the errors and was about to submit a PR too ! Thanks for this.

**Comment by RohitKochhar** [comment]
spider-man-meme

**Comment by mehalter** [comment]
Sorry @tobihans and @RohitKochhar for my blunder 😢 I promise my PR will have been worth it once it's working 😅

**Comment by RohitKochhar** [comment]
No need to apologize! It was a lot quick catch and you got the fix in, that's what matters.

Thanks for the contribution!

**Comment by jbfredheim** [comment]
Just found this issue myself whilst re-configuring my setup and came here to make a PR, Have tested and can confirm %s/optionations/operations/g fixed it completely.
Seems you're on top of things though

**Review by antosha417 — APPROVED** [review]

**Pull request merged**
