### PR TITLE
Triptych integration

### PR DESCRIPTION
**Pull request by simonmclean**
Integration for [Triptych](https://github.com/simonmclean/triptych.nvim/tree/main)

### CODE REVIEW

**Review by antosha417 — APPROVED** [review]
Great job, thank you for you pr!

**Comment by antosha417** [comment]
@simonmclean Do you also want to update Readme to mention [Triptych](https://github.com/simonmclean/triptych.nvim/tree/main)?

**Comment by simonmclean** [comment]
@antosha417 Yes that'd be good. How should I update it? I feel like things would get a bit verbose if there's full setup examples for nvim-tree, neo-tree and triptych for both packer and lazy.

Perhaps just have 1 example for lazy and 1 for packer, and explain that you can include whichever file browser(s) you use in the dependancies list?

**Comment by antosha417** [comment]
@simonmclean Yeah, we can do it like this. 

Another option is to can hide some staff in foldable sections. Like this:
```
<details>
<summary>Summary <b>bold</b></summary>

A lot of hidden ditails here.

</details>
```

I'm open to anything, so you can do as you please. We could also merge like this and I'll update readme later on.

**Comment by simonmclean** [comment]
@antosha417 Okay, I've updated the readme. Let me know if you'd like any changes

**Comment by antosha417** [comment]
Great job! Thank you again for your work 🎉

**Pull request merged**
